### ISSUE TITLE
Bug: Incorrect Base Commit

### ISSUE THREAD

**Issue by tajpouria** [hellofresh/action-changed-files#29]
This is a bug where an HTTPError 404 is being returned when attempting to make a request to the GitHub API for a repository comparison using the base commit "0000000000000000000000000000000000000000". The error message indicates that the requested resource could not be found on the server. The reason for this error is likely due to the fact that the base commit specified is incorrect. "0000000000000000000000000000000000000000" is a null sha1 hash, this means that the commit doesn't exist in the repository and thus it's impossible to compare it with a valid commit sha1 hash.
It's a common mistake when working with git, when specifying a base commit sha1 hash that doesn't exist in the repository it will lead to this error.

```txt
INFO:root:GitHub API request: https://api.github.com/repos/org/repo/compare/0000000000000000000000000000000000000000...48adb89ed9d007de9279ee10f3e693726d099de6
Traceback (most recent call last):
  File "/home/runner/work/_actions/hellofresh/action-changed-files/v3/neo/neo.py", line 245, in <module>
    matrix = main(**args)
  File "/home/runner/work/_actions/hellofresh/action-changed-files/v3/neo/neo.py", line 132, in main
    r = session.get(compare_url)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 662, in send
    r = dispatch_hook('response', hooks, r, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/hooks.py", line 31, in dispatch_hook
    _hook_data = hook(hook_data, **kwargs)
  File "/home/runner/work/_actions/hellofresh/action-changed-files/v3/neo/neo.py", line 119, in <lambda>
    "response": lambda resp, *resp_args, **kwargs: resp.raise_for_status()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.github.com/repos/org/repo/compare/0000000000000000000000000000000000000000...48adb89ed9d007de9279ee10f3e693726d099de6
```

**Comment by tajpouria** [comment]
The issue was temporary.

**Comment by sabrimarzMed** [comment]
this issue is still present. is there anyway we to fix it.
ty

**Comment by Tchekda** [comment]
Just faced this issue as well
